Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]

In [34]:
import numpy as np

arrToRev = np.array([1, 2, 3, 6, 4, 5])
arrToRev[::-1]

array([5, 4, 6, 3, 2, 1])

Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [35]:
arrNoFlat = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
arrNoFlat.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

 Compare the following numpy arrays:
- arr1 = np.array([[1, 2], [3, 4]])
- arr2 = np.array([[1, 2], [3, 4]])

In [36]:
arr1ToComp = np.array([[1, 2], [3, 4]])
arr2ToComp = np.array([[1, 2], [3, 4]])
np.array_equal(arr1ToComp, arr2ToComp)

True

Find the most frequent value and their indice(s) in the following arrays:
- i. x = np.array([1,2,3,4,5,1,2,1,1,1])
- ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [37]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(np.bincount(x).argmax())
print(np.bincount(y).argmax())

1
1


For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
- i. Sum of all elements
- ii. Sum of all elements row-wise
- iii. Sum of all elements column-wise

In [38]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, axis=1))
print(np.sum(gfg, axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
- i. Sum of diagonal elements
- ii. Eigen values of matrix
- iii. Eigen vectors of matrix
- iv. Inverse of matrix
- v. Determinant of matrix

In [39]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
np.trace(n_array)
eigenValues, eigenVectors = np.linalg.eig(n_array)
print(eigenValues)
print(eigenVectors)
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


Multiply the following matrices and also find covariance between matrices using NumPy:
- i. p = [[1, 2], [2, 3]]
- q = [[4, 5], [6, 7]]
- ii. p = [[1, 2], [2, 3], [4, 5]]
- q = [[4, 5, 1], [6, 7, 2]]

In [40]:
p = np.matrix('[1, 2; 2, 3]')
q = np.matrix('[4, 5; 6, 7]')
print(np.matmul(p, q))
p_new = np.matrix('[1, 2; 2, 3; 4, 5]')
q_new = np.matrix('[4, 5, 1; 6, 7, 2]')
print(np.matmul(p_new, q_new))

[[16 19]
 [26 31]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]


For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
- find inner, outer and cartesian product

In [41]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x, y))
print(np.outer(x, y))
print(np.cross(x, y))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
- i. Find element-wise absolute value
- ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
- iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [42]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print(np.abs(array))
array.flatten()
print(np.percentile(array, [25, 50, 75]))
print(np.percentile(array, [25, 50, 75], axis=0))
print(np.percentile(array, [25, 50, 75], axis=1))
print(np.mean(array, axis=0))
print(np.mean(array, axis=1))
print(np.median(array, axis=0))
print(np.median(array, axis=1))
print(np.std(array, axis=0))
print(np.std(array, axis=1))

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]
[-1.5  1.5 -1.5]
[ 1. -4.]
[2.5 3.5 4.5]
[2.05480467 4.78423336]


For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). 
- Find floor, ceiling
and truncated value, rounded values

In [43]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
- i. Sorted array
- ii. Indices of sorted array
- iii. 4 smallest elements
- v. 5 largest elements

In [45]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))
print(np.argsort(array))
print(array[np.argpartition(array, 4)[:4]])
print(array[np.argpartition(array, -5)[-5:]])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
- i. Integer elements only
- ii. Floating elements only

In [46]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array[array % 1 == 0])
print(array[array % 1 != 0])

[1. 2. 3. 2.]
[1.2 2.2]


Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [48]:
import cv2
def img_to_array(path):
    img = cv2.imread(path)
    if len(img.shape) == 3:
        with open('image.txt', 'w') as f:
            for i in img:
                for j in i:
                    f.write(str(j) + '\n')
    else:
        with open('image.txt', 'w') as f:
            for i in img:
                f.write(str(i) + '\n')

img_to_array('./cat.jpg')

Load the saved file into jupyter notebook

In [ ]:
with open('image.txt', 'r') as f:
    print(f.read())